services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db-exam
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: OnlineExam
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_project:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: 2300030796/docker-backend-exam:latest
    container_name: springboot-exam
    ports:
      - "7008:30796"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: 2300030796/docker-frontend-exam:latest
    container_name: react-exam
    ports:
      - "2002:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data_project:

networks:
  springboot-mysql-net:
